<?php

	require DIR_UNITS . 'general/admin/general.controller.xhr.inc';
	require DIR_UNITS . 'users/admin/users.controller.xhr.inc';
	require DIR_UNITS . 'statistics/admin/statistics.controller.xhr.inc';
	require DIR_UNITS . 'catalogs/admin/catalogs.controller.xhr.inc';
	require DIR_UNITS . 'news/admin/news.controller.xhr.inc';
	require DIR_UNITS . 'changes/admin/changes.controller.xhr.inc';
	require DIR_UNITS . 'feedback/admin/feedback.controller.xhr.inc';