<?php

	require DIR_UNITS . 'composition/admin/composition.controller.html.inc';
	require DIR_UNITS . 'general/admin/general.controller.html.inc';
	require DIR_UNITS . 'users/admin/users.controller.html.inc';
	require DIR_UNITS . 'statistics/admin/statistics.controller.html.inc';
	require DIR_UNITS . 'catalogs/admin/catalogs.controller.html.inc';
	require DIR_UNITS . 'news/admin/news.controller.html.inc';
	require DIR_UNITS . 'changes/admin/changes.controller.html.inc';
	require DIR_UNITS . 'feedback/admin/feedback.controller.html.inc';