<?php

	require DIR_UNITS . 'general/site/general.controller.xhr.inc';
	require DIR_UNITS . 'users/site/users.controller.xhr.inc';
	require DIR_UNITS . 'statistics/site/statistics.controller.xhr.inc';
	require DIR_UNITS . 'catalogs/site/catalogs.controller.xhr.inc';
	require	DIR_UNITS . 'news/site/news.controller.xhr.inc';
	require DIR_UNITS . 'changes/site/changes.controller.xhr.inc';
	require DIR_UNITS . 'feedback/site/feedback.controller.xhr.inc';