<?php

	require DIR_UNITS . 'users/site/users.controller.inc';
	require DIR_UNITS . 'statistics/site/statistics.controller.inc';
	require DIR_UNITS . 'catalogs/site/catalogs.controller.inc';
	require	DIR_UNITS . 'news/site/news.controller.inc';
	require DIR_UNITS . 'changes/site/changes.controller.inc';
	require DIR_UNITS . 'feedback/site/feedback.controller.inc';
	require DIR_UNITS . 'pages/site/pages.controller.inc';