<?php

	require 'fields/fieldID.inc';
	require 'fields/fieldBool.inc';
	require 'fields/fieldInt8.inc';
	require 'fields/fieldInt16.inc';
	require 'fields/fieldInt24.inc';
	require 'fields/fieldInt32.inc';
	require 'fields/fieldInt64.inc';
	require 'fields/fieldUInt8.inc';
	require 'fields/fieldUInt16.inc';
	require 'fields/fieldUInt24.inc';
	require 'fields/fieldUInt32.inc';
	require 'fields/fieldUInt64.inc';
	require 'fields/fieldFloat.inc';
	require 'fields/fieldDouble.inc';
	require 'fields/fieldTimestamp.inc';
	require 'fields/fieldEnum.inc';
	require 'fields/fieldSet.inc';
	require 'fields/fieldString.inc';
	require 'fields/fieldText.inc';