<?php

	namespace Proj\Templates\Site\Versions
	{
		const COMMON_JS							= '1.0.0002';		// "/proj/templates/site/js/common.js":729732138
		const CATALOGS_JS						= '1.0.0022';		// "/proj/templates/site/js/catalogs.js":3493341004
		const SKIN_SELECT_JS					= '1.0.0002';		// "/proj/templates/site/js/skins/select.js":1584323857

		const MAIN_CSS							= '1.0.0025';		// "/proj/templates/site/css/main.css":2037073375
	}